### ISSUE TITLE
Game crashing if stand on charging pad with draconic item in inventory

### ISSUE THREAD

**Issue by just4ndy** [ZelGimi/industrialupgrade#10]
I've stood on charging pad having Draconic Axe from Draconic Evloution and my game crashed with this error:

java.lang.ClassCastException: com.brandon3055.draconicevolution.items.tools.DraconicAxe cannot be cast to com.denfop.api.item.IEnergyItem
	at com.denfop.utils.ElectricItemManager.charge(ElectricItemManager.java:34)
	at com.denfop.tiles.base.TileElectricBlock.chargeitems(TileElectricBlock.java:334)
	at com.denfop.tiles.base.TileElectricBlock.getItems(TileElectricBlock.java:290)
	at com.denfop.tiles.base.TileElectricBlock.updateEntityServer(TileElectricBlock.java:483)
	at com.denfop.tiles.base.TileEntityBlock.func_73660_a(TileEntityBlock.java:364)
	at com.zeitheron.hammercore.asm.McHooks.tickTile(McHooks.java:38)
	at net.minecraft.world.World.func_72939_s(World.java:2125)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:742)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:976)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:828)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:687)
	at java.lang.Thread.run(Thread.java:748)

**Comment by ZelGimi** [comment]
fixed
