### ISSUE TITLE
Crash with applied energistics 2

### ISSUE THREAD

**Issue by SrYthan** [ZelGimi/industrialupgrade#107]
at appeng.me.cache.EnergyGridCache.getEnergyDemand(EnergyGridCache.java:370)
	at appeng.me.cache.EnergyGridCache.getEnergyDemand(EnergyGridCache.java:492)
	at appeng.tile.networking.TileEnergyAcceptor.getFunnelPowerDemand(TileEnergyAcceptor.java:82)
	at appeng.tile.powersink.AERootPoweredTile.getExternalPowerDemand(AERootPoweredTile.java:74)
	at appeng.tile.powersink.IC2.getDemandedEnergy(IC2.java:50)
	at aroma1997.uncomplication.enet.EnergyNetLocal.emitEnergyFrom(EnergyNetLocal.java:150)
	at aroma1997.uncomplication.enet.EnergyNetLocal.onTickEnd(EnergyNetLocal.java:533)
	at aroma1997.uncomplication.enet.EnergyNetGlobal.onTickEnd(EnergyNetGlobal.java:94)
	at aroma1997.uncomplication.enet.EventHandler.tick(EventHandler.java:46)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_581_EventHandler_tick_WorldTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:149)
	at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:260)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1006)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:842)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:692)
	at java.lang.Thread.run(Thread.java:748)

**Comment by ZelGimi** [comment]
check RC5
