### ISSUE TITLE
IU crashes when using Neutroniam solar panel and baryon solar panel and having reskillable installed

### ISSUE THREAD

**Issue by allforone33** [ZelGimi/industrialupgrade#119]
java.lang.NullPointerException: Null string not allowed
    at java.util.Objects.requireNonNull(Objects.java:228)
    at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:19)
    at net.minecraft.nbt.NBTTagCompound.setString(NBTTagCompound.java:138)
    at com.denfop.tiles.panels.entity.TileEntitySolarPanel.writeToNBT(TileEntitySolarPanel.java:345)
    at codersafterdark.reskillable.base.LevelLockHandler.rightClickBlock(LevelLockHandler.java:334)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3133_LevelLockHandler_rightClickBlock_RightClickBlock.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:1137)
    at net.minecraft.client.multiplayer.PlayerControllerMP.processRightClickBlock(PlayerControllerMP.java:398)
    at net.minecraft.client.Minecraft.redirect$zba000$rightClickBlockProxy(Minecraft.java:3362)
    at net.minecraft.client.Minecraft.rightClickMouse(Minecraft.java:1579)
    at net.minecraft.client.Minecraft.processKeyBinds(Minecraft.java:2254)
    at net.minecraft.client.Minecraft.runTickKeyboard(Minecraft.java:2020)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1808)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:5114)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
    at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
    at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
    at org.polymc.EntryPoint.listen(EntryPoint.java:144)
    at org.polymc.EntryPoint.main(EntryPoint.java:74)

**Comment by ZelGimi** [comment]
Check in RC7

**Comment by ZelGimi** [comment]
fix
