### ISSUE TITLE
Crash start up 1.12.2

### ISSUE THREAD

**Issue by FomaDima** [ZelGimi/industrialupgrade#162]
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Industrial Upgrade (industrialupgrade)
Caused by: java.util.NoSuchElementException: No value present
    at java.util.Optional.get(Unknown Source)
    at com.denfop.integration.ae.AEIntegration.init(AEIntegration.java:16)
    at com.denfop.proxy.CommonProxy.registerRecipe(CommonProxy.java:528)
    at com.denfop.proxy.ClientProxy.registerRecipe(ClientProxy.java:201)
    at com.denfop.IUCore.init(IUCore.java:382)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
    at net.minecraft.client.Minecraft.init(Minecraft.java:535)
    at net.minecraft.client.Minecraft.run(Minecraft.java:7101)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:234)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:269)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by FomaDima** [comment]
IndustrialUpgrade-1.12.2-2.5.0.4.jar

**Comment by ZelGimi** [comment]
Are you running your version of ae2?

**Comment by FomaDima** [comment]
appliedenergistics2-rv6-stable-7-extended_life-v0.55.13

**Comment by FomaDima** [comment]
try IndustrialUpgrade-1.12.2-2.5.0.6.jar dont work...
I do not even know. I'm trying to disable other mods, suddenly it's not your mod's fault. While the problem remains. I'll keep trying mods.  sorry for the bad english - I use a translator.

**Comment by Rambo28456** [comment]
У меня стоит версия мода IndustrialUpgrade-1.12.2-2.5.0.5 и appliedenergistics2-rv6-stable-7-extended_life-v0.55.13,
все работает хорошо. От некоторых вылетов я избавился с помощью Optifine, удалил его, может и вам поможет

**Comment by ZelGimi** [comment]
did you change the ae2 config?

**Comment by FomaDima** [comment]
yep... 
sorry. Used mod pack. And I did not know that there is such an option in the config - and it can influence this way. My fault. Yes, now it works .. For those who will google, here is the solution in the config - client {
    # Possible Values: AE, EU, RF, GTEU
