### ISSUE TITLE
Подсказка об ошибке для солнечных модулей

### ISSUE THREAD

**Issue by 366602633** [ZelGimi/industrialupgrade#38]
When my mouse hovers over the solar module, the tooltip correctly shows 'perfect recycler' and all the previous machines, but afterward, an tooltip error appears. 

Когда мой курсор наводится на солнечный модуль, всплывающая подсказка правильно показывает 'идеальный переработчик' и все предыдущие машины, но затем появляется ошибка в подсказке.

```sh
[20:09:36] [Client thread/ERROR] [jei]: Failed to get tooltip: 1xiu.m.modulestype@0 industrialupgrade:modulestype
java.lang.IndexOutOfBoundsException: Index: 20, Size: 10
	at java.util.ArrayList.rangeCheck(ArrayList.java:659) ~[?:1.8.0_401]
	at java.util.ArrayList.get(ArrayList.java:435) ~[?:1.8.0_401]
	at java.util.Collections$UnmodifiableList.get(Collections.java:1311) ~[?:1.8.0_401]
	at com.denfop.items.block.ItemBlockTileEntity.getTeBlock(ItemBlockTileEntity.java:112) ~[ItemBlockTileEntity.class:3.2.0.9]
	at com.denfop.items.block.ItemBlockTileEntity.func_77667_c(ItemBlockTileEntity.java:60) ~[ItemBlockTileEntity.class:3.2.0.9]
	at net.minecraft.item.ItemStack.func_77977_a(ItemStack.java:509) ~[aip.class:?]
	at com.denfop.items.modules.ItemModuleTypePanel.func_77624_a(ItemModuleTypePanel.java:81) ~[ItemModuleTypePanel.class:3.2.0.9]
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:707) ~[aip.class:?]
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackRenderer.getTooltip(ItemStackRenderer.java:42) [ItemStackRenderer.class:?]
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackRenderer.getTooltip(ItemStackRenderer.java:23) [ItemStackRenderer.class:?]
	at mezz.jei.render.IngredientRenderer.getIngredientTooltipSafe(IngredientRenderer.java:138) [IngredientRenderer.class:?]
	at mezz.jei.render.IngredientRenderer.getTooltip(IngredientRenderer.java:109) [IngredientRenderer.class:?]
	at mezz.jei.render.IngredientRenderer.drawTooltip(IngredientRenderer.java:90) [IngredientRenderer.class:?]
	at mezz.jei.gui.overlay.IngredientGrid.drawTooltips(IngredientGrid.java:119) [IngredientGrid.class:?]
	at mezz.jei.gui.overlay.IngredientGridWithNavigation.drawTooltips(IngredientGridWithNavigation.java:102) [IngredientGridWithNavigation.class:?]
	at mezz.jei.gui.overlay.IngredientListOverlay.drawTooltips(IngredientListOverlay.java:173) [IngredientListOverlay.class:?]
	at mezz.jei.gui.GuiEventHandler.onDrawScreenEventPost(GuiEventHandler.java:119) [GuiEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_923_GuiEventHandler_onDrawScreenEventPost_Post.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:397) [ForgeHooksClient.class:?]
	at sun.reflect.GeneratedMethodAccessor30.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_401]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_401]
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:669) [Reflector.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1462) [buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_401]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_401]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_401]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_401]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_401]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_401]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_401]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_401]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:110) [JavaWrapper.jar:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:103) [JavaWrapper.jar:?]
```

Only the solar module has this issue.
Только у солнечного модуля есть эта проблема.

**Comment by 366602633** [comment]
The versions of the modules for testing are 3.2.0.9 and 3.2.0.8.
Версии модулей для тестирования — 3.2.0.9 и 3.2.0.8.

**Comment by ZelGimi** [comment]
Fixed in 3.3
