### ISSUE TITLE
ExtraCells crash and render issues

### ISSUE THREAD

**Issue by DarkVen0m** [ZelGimi/industrialupgrade#39]
All liquids from the mod are not rendered correctly inside fluid terminal
![2021-11-27_11-21-43](https://user-images.githubusercontent.com/16627883/143674034-50446060-b74d-406d-9d61-802ac34b55a4.png)

Render inside fluid interface causes game crash with following trace

Minecraft 1.7.10
IndustrialUpgrade 2.5.13
ExtraCells 2.3.14b200

Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at net.minecraft.client.gui.Gui.func_94065_a(SourceFile:117)
	at extracells.gui.widget.WidgetFluidTank.draw(WidgetFluidTank.java:60)
	at extracells.gui.GuiFluidInterface.func_146979_b(GuiFluidInterface.java:74)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:119)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1455)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.gui.Gui.func_94065_a(SourceFile:117)
	at extracells.gui.widget.WidgetFluidTank.draw(WidgetFluidTank.java:60)
	at extracells.gui.GuiFluidInterface.func_146979_b(GuiFluidInterface.java:74)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:119)

**Comment by ZelGimi** [comment]
Thanks for the bug, this bug fixed, wait 2.5.14

**Comment by DarkVen0m** [comment]
Seems to be fixed. Closing the issue.
