### ISSUE TITLE
Достижения с жидкостными контейнерами устарели или предметы не зарегистрированы должным образом

### ISSUE THREAD

**Issue by 366602633** [ZelGimi/industrialupgrade#39]
An error occurred when registering the achievement for the fluid, causing the achievement to not display correctly.
Ошибка при регистрации достижения для жидкости привела к тому, что достижение не отображается корректно.

```shell
[19:52:52] [Server thread/ERROR] [FML]: Parsing error loading built-in advancement industrialupgrade:main/petrol
com.google.gson.JsonSyntaxException: Expected item to be an item, was unknown string 'industrialupgrade:itemcell'
	at net.minecraft.util.JsonUtils.func_188172_b(SourceFile:124) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.func_188180_i(SourceFile:135) ~[rc.class:?]
	at net.minecraft.advancements.DisplayInfo.func_193221_a(DisplayInfo.java:133) ~[r.class:?]
	at net.minecraft.advancements.DisplayInfo.func_192294_a(DisplayInfo.java:111) ~[r.class:?]
	at net.minecraft.advancements.Advancement$Builder.func_192059_a(SourceFile:202) ~[i$a.class:?]
	at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
	at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
	at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:492) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.func_188176_a(SourceFile:517) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.func_188178_a(SourceFile:537) ~[rc.class:?]
	at net.minecraftforge.common.ForgeHooks.lambda$loadAdvancements$0(ForgeHooks.java:1381) ~[ForgeHooks.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:833) [CraftingHelper.class:?]
	at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1359) [ForgeHooks.class:?]
	at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1326) [ForgeHooks.class:?]
	at net.minecraft.advancements.AdvancementManager.func_192779_a(AdvancementManager.java:69) [ns.class:?]
	at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
	at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:156) [oo.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:133) [chd.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:233) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_401]
```

**Comment by ZelGimi** [comment]
achievements will be removed in the future and converted into a guidebook
