### ISSUE TITLE
Ошибка в сборке 1.12.2 пишет проблема в Advanced Solar Panels

### ISSUE THREAD

**Issue by FunatiXX** [ZelGimi/industrialupgrade#43]
Привет у меня проблема с сборкой на 1.12.2 forge 14.23.5.2859 пишет проблема в Advanced Solar Panels и Power Utilities.
Обращался в форум Minecraft inside сказали сюда написать.
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2024-10-23 20:20:42 MSK
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Power Utilities (powerutils)
Caused by: java.lang.NoSuchMethodError: com.denfop.recipe.CraftingManager.addRecipe(Lnet/minecraft/item/ItemStack;[Ljava/lang/Object;)V
    at com.powerutils.PowerUtils.init(PowerUtils.java:57)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 3092139016 bytes (2948 MB) / 6878658560 bytes (6560 MB) up to 17146314752 bytes (16352 MB)
  JVM Flags: 7 total; -Xmx16337M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2859 67 mods loaded, 67 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                         | Version           | Source                                  | Signature                                |
       |:----- |:-------------------------- |:----------------- |:--------------------------------------- |:---------------------------------------- |
       | LCHI  | minecraft                  | 1.12.2            | minecraft.jar                           | None                                     |
       | LCHI  | mcp                        | 9.42              | minecraft.jar                           | None                                     |
       | LCHI  | aearlymodloader            | 8.7.1             | minecraft.jar                           | None                                     |
       | LCHI  | FML                        | 8.0.99.99         | forge-1.12.2-14.23.5.2859.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHI  | forge                      | 14.23.5.2859      | forge-1.12.2-14.23.5.2859.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHI  | micdoodlecore              |                   | minecraft.jar                           | None                                     |
       | LCHI  | xaerominimap_core          | 1.12.2-1.0        | minecraft.jar                           | None                                     |
       | LCHI  | xaeroworldmap_core         | 1.12.2-1.0        | minecraft.jar                           | None                                     |
       | LCHI  | obfuscate                  | 0.4.2             | minecraft.jar                           | None                                     |
       | LCHI  | ic2                        | 2.8.170-ex112     | industrialcraft-2-2.8.170-ex112.jar     | de041f9f6187debbc77034a344134053277aa3b0 |
       | LCHI  | industrialupgrade          | 3.2.0.11          | IndustrialUpgrade-1.12.2-3.2.0.11.jar   | None                                     |
       | LCHE  | powerutils                 | 1.5.3             | Power+Utilities.jar                     | None                                     |
       | LCH   | advanced_solar_panels      | 4.3.0             | Advanced+Solar+Panels-4.3.0.jar         | None                                     |
       | LCH   | aiimprovements             | 0.0.1.3           | AIImprovements-1.12-0.0.1b3.jar         | None                                     |
       | LCH   | jei                        | 4.16.1.1012       | jei_1.12.2-4.16.1.1012.jar              | None                                     |
       | LCH   | quark                      | r1.6-179          | Quark-r1.6-179.jar                      | None                                     |
       | LCH   | autoreglib                 | 1.3-32            | AutoRegLib-1.3-32.jar                   | None                                     |
       | LCH   | bcfuelsforic2              | 1.0               | BCFuelsForIC2-0.3.jar                   | None                                     |
       | LCH   | byg                        | 1.7.2             | BiomesYouGo_1.7.2.jar                   | None                                     |
       | LCH   | buildcraftlib              | 7.99.24.8         | buildcraft-all-7.99.24.8.jar            | None                                     |
       | LCH   | buildcraftcore             | 7.99.24.8         | buildcraft-all-7.99.24.8.jar            | None                                     |
       | LCH   | buildcraftbuilders         | 7.99.24.8         | buildcraft-all-7.99.24.8.jar            | None                                     |
       | LCH   | buildcrafttransport        | 7.99.24.8         | buildcraft-all-7.99.24.8.jar            | None                                     |
       | LCH   | buildcraftsilicon          | 7.99.24.8         | buildcraft-all-7.99.24.8.jar            | None                                     |
       | LCH   | buildcraftenergy           | 7.99.24.8         | buildcraft-all-7.99.24.8.jar            | None                                     |
       | LCH   | forestry                   | 5.8.2.422         | forestry_1.12.2-5.8.2.422.jar           | None                                     |
       | LCH   | theoneprobe                | 1.4.28            | theoneprobe-1.12-1.4.28.jar             | None                                     |
       | LCH   | buildcraftcompat           | 7.99.24.8         | buildcraft-all-7.99.24.8.jar            | None                                     |
       | LCH   | buildcraftfactory          | 7.99.24.8         | buildcraft-all-7.99.24.8.jar            | None                                     |
       | LCH   | buildcraftrobotics         | 7.99.24.8         | buildcraft-all-7.99.24.8.jar            | None                                     |
       | LCH   | chameleon                  | 1.12-4.1.3        | Chameleon-1.12-4.1.3.jar                | None                                     |
       | LCH   | ctm                        | MC1.12.2-1.0.2.31 | CTM-MC1.12.2-1.0.2.31.jar               | None                                     |
       | LCH   | chisel                     | MC1.12.2-1.0.2.45 | Chisel-MC1.12.2-1.0.2.45.jar            | None                                     |
       | LCH   | clumps                     | 3.1.2             | Clumps-3.1.2.jar                        | None                                     |
       | LCH   | elevatorid                 | 1.3.14            | ElevatorMod-1.12.2-1.3.14.jar           | None                                     |
       | LCH   | fpsreducer                 | mc1.12.2-1.20     | FpsReducer-mc1.12.2-1.20.jar            | None                                     |
       | LCH   | cfm                        | 6.3.0             | furniture-6.3.2-1.12.2.jar              | None                                     |
       | LCH   | galacticraftcore           | 4.0.2.280         | GalacticraftCore-1.12.2-4.0.2.280.jar   | None                                     |
       | LCH   | gravestone                 | 1.10.3            | gravestone-1.10.3.jar                   | None                                     |
       | LCH   | gravisuite                 | 3.1.1             | GravitationSuite_1.12.2_3.1.1.jar       | None                                     |
       | LCH   | cgm                        | 0.15.3            | guns-0.15.3-1.12.2.jar                  | None                                     |
       | LCH   | hbm                        | hbm-1.8.4a-G      | hbm-1.8.4a-G.jar                        | None                                     |
       | LCH   | ironchest                  | 1.12.2-7.0.67.844 | ironchest_1.12.2_7.0.72.847.jar         | None                                     |
       | LCH   | ironfurnaces               | 1.3.5             | ironfurnaces-1.3.5.jar                  | None                                     |
       | LCH   | jeresources                | 0.9.2.60          | JustEnoughResources-1.12.2-0.9.2.60.jar | None                                     |
       | LCH   | mcef                       | 1.11              | mcef-1.12.2-1.11.jar                    | None                                     |
       | LCH   | mcwbridges                 | 1.0.6             | mcw-bridges-1.0.6b-mc1.12.2.jar         | None                                     |
       | LCH   | mcwdoors                   | 1.3               | mcw-doors-1.0.3-mc1.12.2.jar            | None                                     |
       | LCH   | mcwfences                  | 1.0.0             | mcw-fences-1.0.0-mc1.12.2.jar           | None                                     |
       | LCH   | mcwfurnitures              | 1.0.1             | mcw-furniture-1.0.1-mc1.12.2beta.jar    | None                                     |
       | LCH   | mcwlights                  | 1.0.6             | mcw-lights-1.0.6-mc1.12.2forge.jar      | None                                     |
       | LCH   | mcwpaintings               | 1.0.5             | mcw-paintings-1.0.5-1.12.2forge.jar     | None                                     |
       | LCH   | mcwpaths                   | 1.0.2             | mcw-paths-1.0.2forge-mc1.12.2.jar       | None                                     |
       | LCH   | mcwtrpdoors                | 1.0.2             | mcw-trapdoors-1.0.3-mc1.12.2.jar        | None                                     |
       | LCH   | mcwwindows                 | 1.0               | mcw-windows-1.0.0-mc1.12.2.jar          | None                                     |
       | LCH   | mousetweaks                | 2.10.1            | MouseTweaks-2.10.1-mc1.12.2.jar         | None                                     |
       | LCH   | neid                       | 1.5.4.4           | NotEnoughIDs-1.5.4.4.jar                | None                                     |
       | LCH   | pixelmon                   | 8.7.1             | PixelmonGenerations-1.12.2-8.7.1.jar    | None                                     |
       | LCH   | storagedrawers             | 5.5.2             | StorageDrawers-1.12.2-5.5.2.jar         | None                                     |
       | LCH   | tlauncher_custom_cape_skin | 1.4               | tlskincape1.12.2-1.4.jar                | None                                     |
       | LCH   | treechop                   | 0.14.6            | TreeChop-1.12.2-0.14.7.jar              | None                                     |
       | LCH   | vanillafix                 | 1.0.10-150        | VanillaFix-1.0.10-150.jar               | None                                     |
       | LCH   | vehicle                    | 0.44.1            | vehicle-mod-0.44.1-1.12.2.jar           | None                                     |
       | LCH   | waystones                  | 4.1.0             | Waystones_1.12.2-4.1.0.jar              | None                                     |
       | LCH   | webdisplays                | 1.1               | webdisplays-1.12.2-1.1.jar              | None                                     |
       | LCH   | xaerominimap               | 24.4.1            | Xaeros_Minimap_24.4.1_Forge_1.12.jar    | None                                     |
       | LCH   | xaeroworldmap              | 1.39.0            | XaerosWorldMap_1.39.0_Forge_1.12.jar    | None                                     |
  Loaded coremods (and transformers): EarlyLoadPlugin (PixelmonGenerations-1.12.2-8.7.1.jar)
                                        com.pixelmongenerations.core.plugin.PixelmonTransformer
                                      Plugin (NotEnoughIDs-1.5.4.4.jar)
                                        ru.fewizz.neid.asm.Transformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      ShutdownPatcher (mcef-1.12.2-1.11-coremod.jar)
                                        net.montoyo.mcef.coremod.ShutdownPatcher
                                      MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
                                        micdoodle8.mods.miccore.MicdoodleTransformer
                                      Quark Plugin (Quark-r1.6-179.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      TLSkinCapeHookLoader (tlskincape1.12.2-1.4.jar)
                                        gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
                                      XaeroMinimapPlugin (Xaeros_Minimap_24.4.1_Forge_1.12.jar)
                                        xaero.common.core.transformer.ChunkTransformer
                                        xaero.common.core.transformer.NetHandlerPlayClientTransformer
                                        xaero.common.core.transformer.EntityPlayerTransformer
                                        xaero.common.core.transformer.AbstractClientPlayerTransformer
                                        xaero.common.core.transformer.WorldClientTransformer
                                        xaero.common.core.transformer.EntityPlayerMPTransformer
                                        xaero.common.core.transformer.EntityPlayerSPTransformer
                                        xaero.common.core.transformer.PlayerListTransformer
                                        xaero.common.core.transformer.SaveFormatTransformer
                                        xaero.common.core.transformer.GuiIngameForgeTransformer
                                        xaero.common.core.transformer.MinecraftServerTransformer
                                        xaero.common.core.transformer.GuiBossOverlayTransformer
                                        xaero.common.core.transformer.ModelRendererTransformer
                                      XaeroWorldMapPlugin (XaerosWorldMap_1.39.0_Forge_1.12.jar)
                                        xaero.map.core.transformer.ChunkTransformer
                                        xaero.map.core.transformer.NetHandlerPlayClientTransformer
                                        xaero.map.core.transformer.EntityPlayerTransformer
                                        xaero.map.core.transformer.AbstractClientPlayerTransformer
                                        xaero.map.core.transformer.WorldClientTransformer
                                        xaero.map.core.transformer.EntityPlayerMPTransformer
                                        xaero.map.core.transformer.PlayerListTransformer
                                        xaero.map.core.transformer.SaveFormatTransformer
                                        xaero.map.core.transformer.BiomeColorHelperTransformer
                                        xaero.map.core.transformer.MinecraftServerTransformer
                                        xaero.map.core.transformer.MinecraftTransformer
                                      ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
                                        com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
  GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.0 Compatibility Profile Context 24.3.1.240216' Renderer: 'Radeon RX 580 Series'
  Suspected Mods: Power Utilities (powerutils)
  Launched Version: oj
  LWJGL: 2.9.4
  OpenGL: Radeon RX 580 Series GL version 4.6.0 Compatibility Profile Context 24.3.1.240216, ATI Technologies Inc.
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: Русский (Россия)
  Profiler Position: N/A (disabled)
  CPU: 4x Intel(R) Core(TM) i5-4430 CPU @ 3.00GHz

P.s. Привет от Шара)

**Comment by ZelGimi** [comment]
Power Utilities старая версия, обновите

**Comment by FunatiXX** [comment]
спасибо сработало!
