### ISSUE TITLE
虽然可能没人会用了但是 和战术框架(TacticalFrame)同时装载会崩溃[1.7.10]

### ISSUE THREAD

**Issue by shen-suan-zi** [ZelGimi/industrialupgrade#47]
日志糊脸：
Time: 21-12-15 下午3:27
Description: Exception in server tick loop

java.lang.RuntimeException: ambiguous recipe: [[1xic2.itemIngot@6, 1xitem.ingot@14, 1xitem.substituteingot@0] -> [1xitem.plate@14]]
	at ic2.core.BasicMachineRecipeManager.displayError(BasicMachineRecipeManager.java:306)
	at ic2.core.BasicMachineRecipeManager.addRecipe(BasicMachineRecipeManager.java:40)
	at com.denfop.recipes.MetalFormerRecipe.addmolot(MetalFormerRecipe.java:44)
	at com.denfop.recipes.MetalFormerRecipe.init(MetalFormerRecipe.java:18)
	at com.denfop.proxy.CommonProxy.registerRecipe(CommonProxy.java:416)
	at com.denfop.IUCore.Init(IUCore.java:284)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
	at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by ZelGimi** [comment]
Give me your list mods

**Comment by shen-suan-zi** [comment]
this is the list in crash-reports:
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHI	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHI	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHI	OmniOcularCore{1.0} [Omni Ocular Core] (minecraft.jar) 
	UCHI	NotEnoughItems{1.0.5.120} [Not Enough Items] ([NEI]NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHI	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHI	IC2{2.2.828-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.828-experimental[工业时代2].jar) 
	UCHI	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar) 
	UCHE	industrialupgrade{2.5.17} [Industrial Upgrade] (IndustrialUpgrade-2.5.17.jar) 
	UCHI	TacticalFrame{0.9.73} [TacticalFrame Mod] (战术框架1.7.10.jar) 
	UCHI	Waila{1.5.10} [Waila] ([NEI附属-高亮信息拓展]Waila-1.5.10_1.7.10.jar) 
	UCHI	OmniOcular{1.7.10-1.0build103} [Omni Ocular] ([NBT显示]OmniOcular-1.7.10-1.0build103.jar) 
	UCHI	NBTEdit{1.7.2.2} [In-game NBTEdit] ([NBT编辑器]NBTEdit_1.7.10.jar) 
	UCHI	neresources{0.1.0.ManuallyBuilt} [Not Enough Resources] ([NEI附属-NER]NotEnoughResources-1.7.10-0.1.0-122.jar) 
	UCHI	NEIAddons{1.12.14.40} [NEI Addons] ([NEI附属]neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHI	NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools] ([NEI附属]neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHI	NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2] ([NEI附属]neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHI	NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany] ([NEI附属]neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHI	NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry] ([NEI附属]neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHI	NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables] ([NEI附属]neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCHI	NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo] ([NEI附属]neiaddons-1.12.14.40-mc1.7.10.jar) 
	CoFHCore: -[1.7.10]3.1.4-329

**Comment by shen-suan-zi** [comment]
and one more thing...
will you update the chinese lang file?

**Comment by MakandIv** [comment]
> will you update the chinese lang file?

For 1.12.2 updated by 绝绝子.

**Comment by ZelGimi** [comment]
Fixed 2.5.19

**Comment by shen-suan-zi** [comment]
> > will you update the chinese lang file?
> 
> For 1.12.2 updated by 绝绝子.

So there is no 1.7.10？

**Comment by MakandIv** [comment]
On 1.7.10, unfortunately, no. In principle, from 1.12.2 can be remade into 1.7.10, but I'm afraid there may be different names. I will not do this, I do not know Chinese.

**Comment by shen-suan-zi** [comment]
alright... i will try to do it myself
