### ISSUE TITLE
about industrialupgrade.basemachine1.magnet_generator=电磁发电机 carsh  the server when placed it

### ISSUE THREAD

**Issue by 233littileone** [ZelGimi/industrialupgrade#56]
[16:10:02] [Server thread/INFO] [net.minecraft.server.management.PlayerList]: Wlater_Sullivan logged in with entity id 665 at ([sc]-124.3167860906635, 75.0, -516.8355704679767)
[16:10:02] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$WorldTickEvent@3a76af34:
java.lang.NoClassDefFoundError: net/minecraft/client/gui/GuiScreen
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_281]
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source) ~[?:1.8.0_281]
	at java.lang.Class.getDeclaredMethod(Unknown Source) ~[?:1.8.0_281]
	at ic2.core.block.TileEntityBlock.requiresWorldTick(TileEntityBlock.java:1028) ~[TileEntityBlock.class:?]
	at ic2.core.block.TileEntityBlock.onLoaded(TileEntityBlock.java:191) ~[TileEntityBlock.class:?]
	at com.denfop.tiles.base.TileEntityElectricMachine.onLoaded(TileEntityElectricMachine.java:65) ~[TileEntityElectricMachine.class:2.2]
	at ic2.core.block.TileEntityBlock$1.onTick(TileEntityBlock.java:171) ~[TileEntityBlock$1.class:?]
	at ic2.core.TickHandler.processUpdates(TickHandler.java:148) ~[TickHandler.class:?]
	at ic2.core.TickHandler.onWorldTick(TickHandler.java:35) ~[TickHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_609_TickHandler_onWorldTick_WorldTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:git-CatServer-1.12.2-c0537be]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190) [EventBus.class:git-CatServer-1.12.2-c0537be]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:289) [FMLCommonHandler.class:git-CatServer-1.12.2-c0537be]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:946) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:474) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:826) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:685) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.gui.GuiScreen
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	... 18 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@69ca39cd from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:262) ~[CatServer-c0537be-universal.jar:git-CatServer-1.12.2-c0537be]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	... 18 more
Caused by: java.lang.RuntimeException: Attempted to load class blk for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62) ~[CatServer-c0537be-universal.jar:git-CatServer-1.12.2-c0537be]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258) ~[CatServer-c0537be-universal.jar:git-CatServer-1.12.2-c0537be]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	... 18 more
[16:10:02] [Server thread/ERROR] [FML]: Index: 9 Listeners:
[16:10:02] [Server thread/ERROR] [FML]: 0: NORMAL
[16:10:02] [Server thread/ERROR] [FML]: 1: ASM: class com.feed_the_beast.ftblib.lib.data.Universe onTickEvent(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[16:10:02] [Server thread/ERROR] [FML]: 2: ASM: class crazypants.enderio.base.handler.ServerTickHandler onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[16:10:02] [Server thread/ERROR] [FML]: 3: ASM: class crazypants.enderio.base.material.material.MaterialCraftingHandler onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[16:10:02] [Server thread/ERROR] [FML]: 4: ASM: class moe.plushie.armourers_workshop.common.world.SyncWorldUpdater onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[16:10:02] [Server thread/ERROR] [FML]: 5: ASM: class vazkii.botania.common.core.handler.CommonTickHandler onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[16:10:02] [Server thread/ERROR] [FML]: 6: ASM: class flaxbeard.immersivepetroleum.common.EventHandler handleNapalm(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[16:10:02] [Server thread/ERROR] [FML]: 7: ASM: class flaxbeard.immersivepetroleum.common.EventHandler handleLubricatingMachinesServer(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[16:10:02] [Server thread/ERROR] [FML]: 8: ASM: crafttweaker.mc1120.events.CommonEventHandler@4cc6f448 onWorldTickEvent(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[16:10:02] [Server thread/ERROR] [FML]: 9: ASM: ic2.core.TickHandler@53babba9 onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[16:10:02] [Server thread/ERROR] [FML]: 10: ASM: ic2.core.energy.grid.EventHandler@4c12fd32 onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[16:10:02] [Server thread/ERROR] [FML]: 11: ASM: noppes.npcs.ServerTickHandler@2bc7db5f onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[16:10:02] [Server thread/ERROR] [FML]: 12: ASM: mcjty.xnet.ForgeEventHandlers@6fa96451 onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[16:10:02] [Server thread/ERROR] [FML]: 13: ASM: omtteam.omlib.handler.OMLibEventHandler@5166ece2 tickEvent(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[16:10:02] [Server thread/ERROR] [FML]: 14: ASM: morph.avaritia.handler.AvaritiaEventHandler@3f68358b onTickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[16:10:02] [Server thread/ERROR] [FML]: 15: ASM: cofh.thermaldynamics.util.TickHandler@38d9d974 tick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[16:10:02] [Server thread/ERROR] [FML]: 16: ASM: com.valkyrieofnight.et.m_multiblocks.m_nanobot.manager.NBBManager@73593ff4 onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[16:10:02] [Server thread/ERROR] [FML]: 17: ASM: micdoodle8.mods.galacticraft.planets.venus.event.EventHandlerVenus@32eea5bf onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[16:10:02] [Server thread/ERROR] [FML]: 18: ASM: mctmods.immersivetechnology.common.CommonProxy@4a3abb7e onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[16:10:02] [Server thread/ERROR] [FML]: 19: ASM: vazkii.botania.common.item.ItemGrassSeeds@5b4faee5 onTickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[16:10:02] [Server thread/ERROR] [FML]: 20: ASM: vazkii.botania.common.item.equipment.tool.terrasteel.ItemTerraAxe@301e06b7 onTickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[16:10:02] [Server thread/ERROR] [FML]: 21: ASM: com.brandon3055.draconicevolution.world.WorldTickHandler@2daebcb1 tickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[16:10:02] [Server thread/ERROR] [FML]: 22: ASM: blusunrize.immersiveengineering.common.world.IEWorldGen@5465c3e serverWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[16:10:02] [Server thread/ERROR] [FML]: 23: ASM: blusunrize.immersiveengineering.common.EventHandler@729ca55 onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[16:10:02] [Server thread/ERROR] [FML]: 24: ASM: micdoodle8.mods.galacticraft.planets.asteroids.tick.AsteroidsTickHandlerServer@26ee505b onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[16:10:02] [Server thread/ERROR] [FML]: 25: ASM: forestry.core.TickHandlerCoreServer@6147afa3 onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[16:10:02] [Server thread/ERROR] [FML]: 26: ASM: forestry.core.multiblock.MultiblockServerTickHandler@367dd336 onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[16:10:02] [Server thread/ERROR] [FML]: 27: ASM: micdoodle8.mods.galacticraft.core.tick.TickHandlerServer@d95f28b onWorldTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[16:10:02] [Server thread/ERROR] [FML]: 28: ASM: mods.flammpfeil.slashblade.event.ScheduleEntitySpawner@7b7bddfe onWorldTickEvent(Lnet/minecraftforge/fml/common/gameevent/TickEvent$WorldTickEvent;)V
[16:10:02] [Server thread/ERROR] [FML]: 29: ASM: Block{minecraft:air} tickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[16:10:02] [Server thread/ERROR] [FML]: 30: ASM: appeng.hooks.TickHandler@60350b3c onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[16:10:02] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: net/minecraft/client/gui/GuiScreen
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_281]
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source) ~[?:1.8.0_281]
	at java.lang.Class.getDeclaredMethod(Unknown Source) ~[?:1.8.0_281]
	at ic2.core.block.TileEntityBlock.requiresWorldTick(TileEntityBlock.java:1028) ~[TileEntityBlock.class:?]
	at ic2.core.block.TileEntityBlock.onLoaded(TileEntityBlock.java:191) ~[TileEntityBlock.class:?]
	at com.denfop.tiles.base.TileEntityElectricMachine.onLoaded(TileEntityElectricMachine.java:65) ~[TileEntityElectricMachine.class:2.2]
	at ic2.core.block.TileEntityBlock$1.onTick(TileEntityBlock.java:171) ~[TileEntityBlock$1.class:?]
	at ic2.core.TickHandler.processUpdates(TickHandler.java:148) ~[TickHandler.class:?]
	at ic2.core.TickHandler.onWorldTick(TickHandler.java:35) ~[TickHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_609_TickHandler_onWorldTick_WorldTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:git-CatServer-1.12.2-c0537be]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190) ~[EventBus.class:git-CatServer-1.12.2-c0537be]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:289) ~[FMLCommonHandler.class:git-CatServer-1.12.2-c0537be]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:946) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:474) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:826) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:685) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.gui.GuiScreen
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	... 18 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@69ca39cd from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:262) ~[CatServer-c0537be-universal.jar:git-CatServer-1.12.2-c0537be]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	... 18 more
Caused by: java.lang.RuntimeException: Attempted to load class blk for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62) ~[CatServer-c0537be-universal.jar:git-CatServer-1.12.2-c0537be]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258) ~[CatServer-c0537be-universal.jar:git-CatServer-1.12.2-c0537be]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	... 18 more

**Comment by 233littileone** [comment]
same with industrialupgrade.basemachine3.radiation_purifier=辐射净化器
