### ISSUE TITLE
修复了 但没完全修复

### ISSUE THREAD

**Issue by L-i-s-T-m** [ZelGimi/industrialupgrade#65]
java.lang.RuntimeException: ambiguous recipe: [[1xitem.ImmersiveEngineering.metal@3, 1xic2.itemIngot@6, 1xitem.ingot@14, 1xitem.substituteingot@0] -> [1xitem.plate@14]]
	at ic2.core.BasicMachineRecipeManager.displayError(BasicMachineRecipeManager.java:306)
	at ic2.core.BasicMachineRecipeManager.addRecipe(BasicMachineRecipeManager.java:40)
	at com.denfop.recipes.MetalFormerRecipe.addmolot(MetalFormerRecipe.java:47)
	at [com.denfop.recipes.MetalFormerRecipe.init(MetalFormerRecipe.java:18)]

[https://github.com/ZelGimi/industrialupgrade/issues/47](url)

fixed but not completely fixed XD

because "substituteingot" registered ore:ingotIron and ore:ingotGold ?

**Comment by MakandIv** [comment]
Recipe conflict. Do you have your own crafting recipes in the Metal Former?

**Comment by L-i-s-T-m** [comment]
> Recipe conflict. Do you have your own crafting recipes in the Metal Former?

i did not write anything...

**Comment by MakandIv** [comment]
oh, you're on version 1.7.10? Then perhaps this is a bug indeed.
