### ISSUE TITLE
Quantum Drill error

### ISSUE THREAD

**Issue by GoldenLs** [ZelGimi/industrialupgrade#69]
And so I used the Quantum Drill in the ore mining mode.When mining RedStone, the server crashes.
`Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Stack can not be invalid!
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_221]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_221]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:890) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:474) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:826) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:685) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
Caused by: java.lang.IllegalArgumentException: Stack can not be invalid!
	at net.minecraftforge.oredict.OreDictionary.getOreIDs(OreDictionary.java:504) ~[OreDictionary.class:git-CatServer-1.12.2-a8b73e9]
	at com.denfop.items.energy.EnergyDrill.check_list(EnergyDrill.java:926) ~[EnergyDrill.class:2.3.5]
	at com.denfop.items.energy.EnergyDrill.func_179218_a(EnergyDrill.java:619) ~[EnergyDrill.class:2.3.5]
	at net.minecraft.item.ItemStack.func_179548_a(ItemStack.java:434) ~[aip.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:393) ~[or.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180785_a(PlayerInteractionManager.java:304) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:1095) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[lp.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[lp.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_221]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_221]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more`

**Comment by ZelGimi** [comment]
fixed
