### ISSUE TITLE
Sound NullPointerException

### ISSUE THREAD

**Issue by Hexagon-Dev** [ZelGimi/industrialupgrade#91]
Was testing modpack with my friend and he got an exception. Game didn't crash, however maybe it would be helpful.
Btw, friend using optifine and shaders, I know that it is not recommended, but however.
Briefly:
```
Caused by: java.lang.NullPointerException
    at paulscode.sound.SoundSystem.play(SoundSystem.java:1170)
    at com.denfop.audio.AudioSourceClient.play(AudioSourceClient.java:121)
    at com.denfop.tiles.base.TileEntityMultiMachine.onNetworkEvent(TileEntityMultiMachine.java:782)
    at ic2.core.network.NetworkManagerClient$1.run(NetworkManagerClient.java:230)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.func_181617_a(Util.java:529)
    ... 9 more
```
Full report:
[crash-2022-06-14_22.01.29-client.txt](https://github.com/ZelGimi/industrialupgrade/files/8903652/crash-2022-06-14_22.01.29-client.txt)

**Comment by ZelGimi** [comment]
Can you tell me what mechanisms you have on the base?

**Comment by Hexagon-Dev** [comment]
![image](https://user-images.githubusercontent.com/69513821/173686911-a6c8d9e1-c560-4e86-9ff0-f72c80b77d13.png)
![image](https://user-images.githubusercontent.com/69513821/173686952-b95a9e88-16c1-42a4-9d0e-5fb0b2a591a5.png)
Fridge, cutter, extruder, rolling machine, furnance, induction furnance, compressor, electric heater, blast furnance, macerator, extractor, batbox.

**Comment by ZelGimi** [comment]
wait 2.4RC4 and check this bug, if it is fixed - write here what is fixed

**Comment by ZelGimi** [comment]
fixed
