### ISSUE TITLE
Nuclear Reactor from IndustrialUpgrade makes server crash when the rods are depleted

### ISSUE THREAD

**Issue by dvdcorsair** [ZelGimi/industrialupgrade#97]
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 2022-06-29 19:00:13 BST
Description: Ticking block entity

java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:911)
    at java.util.ArrayList$Itr.next(ArrayList.java:861)
    at com.denfop.tiles.reactors.TileEntityBaseNuclearReactorElectric.processChambers(TileEntityBaseNuclearReactorElectric.java:359)
    at com.denfop.tiles.reactors.TileEntityBaseNuclearReactorElectric.updateEntityServer(TileEntityBaseNuclearReactorElectric.java:235)
    at ic2.core.block.TileEntityBlock.func_73660_a(TileEntityBlock.java:331)
    at net.minecraft.world.World.redirect$zzn000$tileEntityUpdate(World.java:4137)
    at net.minecraft.world.World.func_72939_s(World.java:1838)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Block entity being ticked --
  Name: industrialupgrade:adv_reactor // com.denfop.tiles.reactors.TileEntityAdvNuclearReactorElectric
  Block type: ID #263 (industrialupgrade.basemachine1 // ic2.core.block.BlockTileEntity // industrialupgrade:basemachine1)
  Block data value: 0 / 0x0 / 0b0000
  Block location: World: (-2884,51,344), Chunk: (at 12,3,8 in -181,21; contains blocks -2896,0,336 to -2881,255,351), Region: (-6,0; contains chunks -192,0 to -161,31, blocks -3072,0,0 to -2561,255,511)

Even after restart the server is still crashing when chunk with reactor is loaded

**Comment by ZelGimi** [comment]
wait 2.4RC4

**Comment by dvdcorsair** [comment]
When will it be released?

**Comment by ZelGimi** [comment]
left a little

**Comment by ZelGimi** [comment]
fixed
